### PR TITLE
Add navbar, footer, time display with lunox

### PR DESCRIPTION
**Pull request by fernandorpm**
# Add navbar, footer, time display with lunox

## To update
- index.html
- style.css
- main_class.js

## Requirements
- Add a Navigation bar
- Add Three content sections: Books list, Add book form, Contact info.
- Make sure that when you click on any of the links, the main area changes to display only one of the three content sections
- To change the contents of the page, don't use any library or framework, use only plain JavaScript and CSS
- Display the current date below the navigation bar. For this requirement, you should use a library - Luxon

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# Hi team😃,

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- Please complete the linters config according to the current project.
Kindly refer to this [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js) for a reminder.

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by fernandorpm** [comment]
Hello!

Do you care to explain a little bit more about what's wrong with the linters?


I've added the linters following the tutorial proposed by microverse, and up until my 3rd PR, none of the reviewers said it was wrong, so I'd appreciate if you could guide me!

**Comment by MahmoudBakr23** [comment]
At first it was using only Javascript so it's required for the javascript linters, now it's using both Javascript, HTML, and CSS. So, the webhint and lighthouse linters are needed 🥰🙏🏻

Thank you for communicating.

**Comment by fernandorpm** [comment]
I have added the HTML linter, but github didn't catch it! I'll try to commit it directly to the development branch.

About the style linter, at least for me, it is appearing! Look at this printscreen:
image

**Comment by MahmoudBakr23** [comment]
I know that you added the stylelint configs right. 👍🏻

**Comment by fernandorpm** [comment]
The problem was in the `.github/workflows/linters.yml` file!

Thanks for pointing out 😄

**Review by MahmoudBakr23 — APPROVED** [review]
Hi team😃, 

Great work on this project. Everything seems perfect to me 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

### **OPTIONAL**

- [x] Please include a new screenshot to your README file
- [x] It'd be great if you added a live demo link for easier access

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
